/* AUTO-GENERATED by scripts/generate-extended-characters.mjs — do not edit manually */
import type { CharacterDefinition } from './characterTypes'

export const extendedCharacters: readonly CharacterDefinition[] = [
  {
    "id": "shinobi-ext-000",
    "name": "土竜",
    "description": "土竜——里で鍛えた素朴な装い。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-0",
    "ability": {
      "type": "none",
      "name": "素朴な修行",
      "description": "特別な補正なし。堅実な足取りで修行する。"
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "headband",
        "woodenShuriken",
        "sandals"
      ],
      "effect": "none",
      "skinSeed": 0
    }
  },
  {
    "id": "shinobi-ext-001",
    "name": "笹吹",
    "description": "笹吹——夜陰に溶ける装束。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-1",
    "ability": {
      "type": "scoreMultiplier",
      "name": "一閃",
      "description": "獲得スコアが2%増加する。",
      "value": 1.02
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "scroll",
        "coinBag",
        "crest"
      ],
      "effect": "ember",
      "skinSeed": 1
    }
  },
  {
    "id": "shinobi-ext-002",
    "name": "木霊",
    "description": "木霊——砂煙を纏う旅装。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-2",
    "ability": {
      "type": "scoreMultiplier",
      "name": "軽足",
      "description": "獲得スコアが3%増加する。",
      "value": 1.03
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "whiteCloak",
        "mask",
        "armor"
      ],
      "effect": "water",
      "skinSeed": 2
    }
  },
  {
    "id": "shinobi-ext-003",
    "name": "苔丸",
    "description": "苔丸——霧に隠れた忍装束。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-3",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "moonCrest",
        "scarf",
        "scroll"
      ],
      "effect": "gold",
      "skinSeed": 3
    }
  },
  {
    "id": "shinobi-ext-004",
    "name": "砂塵",
    "description": "砂塵——岩窟で磨いた武具。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-4",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "dawnSash",
        "dagger",
        "headband"
      ],
      "effect": "mist",
      "skinSeed": 4
    }
  },
  {
    "id": "shinobi-ext-005",
    "name": "蓬屋",
    "description": "蓬屋——鳥の羽を模した軽装。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-5",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "shield",
        "armor",
        "mask"
      ],
      "effect": "wind",
      "skinSeed": 5
    }
  },
  {
    "id": "shinobi-ext-006",
    "name": "雀隠",
    "description": "雀隠——伝承の巻物を携えた姿。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-6",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "lightningMark",
        "armor",
        "dualBlades"
      ],
      "effect": "fire",
      "skinSeed": 6
    }
  },
  {
    "id": "shinobi-ext-007",
    "name": "蛙飛",
    "description": "蛙飛——戦場を駆けた痕跡のある鎧。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-7",
    "ability": {
      "type": "none",
      "name": "素朴な修行",
      "description": "特別な補正なし。堅実な足取りで修行する。"
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "foxTail",
        "mask",
        "scroll"
      ],
      "effect": "fox",
      "skinSeed": 7
    }
  },
  {
    "id": "shinobi-ext-008",
    "name": "蟻走",
    "description": "蟻走——炎の紋章を背負う姿。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-8",
    "ability": {
      "type": "scoreMultiplier",
      "name": "一閃",
      "description": "獲得スコアが2%増加する。",
      "value": 1.02
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "silverBlade",
        "shoulderPad",
        "headband"
      ],
      "effect": "shadow",
      "skinSeed": 8
    }
  },
  {
    "id": "shinobi-ext-009",
    "name": "狸寝",
    "description": "狸寝——黄金の装飾が施された鎧。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-9",
    "ability": {
      "type": "scoreMultiplier",
      "name": "軽足",
      "description": "獲得スコアが3%増加する。",
      "value": 1.03
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "scarf",
        "dagger",
        "headband"
      ],
      "effect": "moon",
      "skinSeed": 9
    }
  },
  {
    "id": "shinobi-ext-010",
    "name": "狐火",
    "description": "狐火——神域に触れたと言われる装束。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-10",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "helmet",
        "shoulderPad",
        "scroll"
      ],
      "effect": "lightning",
      "skinSeed": 10
    }
  },
  {
    "id": "shinobi-ext-011",
    "name": "灰渡",
    "description": "灰渡——野山を駆ける軽装。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-11",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "none",
      "skinSeed": 11
    }
  },
  {
    "id": "shinobi-ext-012",
    "name": "雀舌",
    "description": "雀舌——森の守り人の装い。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-12",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "leafMark",
        "headband",
        "sandals"
      ],
      "effect": "ember",
      "skinSeed": 12
    }
  },
  {
    "id": "shinobi-ext-013",
    "name": "竹蔵",
    "description": "竹蔵——雨に濡れた蓑姿。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-13",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "mask",
        "sandals",
        "shortSword"
      ],
      "effect": "water",
      "skinSeed": 13
    }
  },
  {
    "id": "shinobi-ext-014",
    "name": "石鍋",
    "description": "石鍋——竹の里の修行着。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-14",
    "ability": {
      "type": "none",
      "name": "素朴な修行",
      "description": "特別な補正なし。堅実な足取りで修行する。"
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "dualBlades",
        "redEyes",
        "scarf"
      ],
      "effect": "gold",
      "skinSeed": 14
    }
  },
  {
    "id": "shinobi-ext-015",
    "name": "流灯",
    "description": "流灯——川辺で鍛えた身軽さ。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-15",
    "ability": {
      "type": "scoreMultiplier",
      "name": "一閃",
      "description": "獲得スコアが2%増加する。",
      "value": 1.02
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "blackFlame",
        "dualBlades",
        "mask"
      ],
      "effect": "mist",
      "skinSeed": 15
    }
  },
  {
    "id": "shinobi-ext-016",
    "name": "雨宿",
    "description": "雨宿——獣の気配を借りた装い。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-16",
    "ability": {
      "type": "scoreMultiplier",
      "name": "軽足",
      "description": "獲得スコアが3%増加する。",
      "value": 1.03
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "windScroll",
        "sandals",
        "scarf"
      ],
      "effect": "wind",
      "skinSeed": 16
    }
  },
  {
    "id": "shinobi-ext-017",
    "name": "霧隠",
    "description": "霧隠——古刹で授かった装束。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-17",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "headband",
        "woodenShuriken",
        "sandals"
      ],
      "effect": "fire",
      "skinSeed": 17
    }
  },
  {
    "id": "shinobi-ext-018",
    "name": "葦刃",
    "description": "葦刃——雷を纏う特異な装備。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-18",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "scroll",
        "coinBag",
        "crest"
      ],
      "effect": "fox",
      "skinSeed": 18
    }
  },
  {
    "id": "shinobi-ext-019",
    "name": "麦藁",
    "description": "麦藁——氷の気配を帯びた外套。",
    "rarity": "N",
    "skinClass": "ninja-skin-gen-19",
    "ability": {
      "type": "none",
      "name": "地味な技",
      "description": "特別な補正なし。地味だが確実な一撃を放つ。"
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "whiteCloak",
        "mask",
        "armor"
      ],
      "effect": "shadow",
      "skinSeed": 19
    }
  },
  {
    "id": "shinobi-ext-020",
    "name": "蒼牙",
    "description": "蒼牙——神域に触れたと言われる装束。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-20",
    "ability": {
      "type": "scoreMultiplier",
      "name": "鋭刃",
      "description": "獲得スコアが5%増加する。",
      "value": 1.05
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "blackFlame",
        "dualBlades",
        "mask"
      ],
      "effect": "gold",
      "skinSeed": 20
    }
  },
  {
    "id": "shinobi-ext-021",
    "name": "紫電",
    "description": "紫電——野山を駆ける軽装。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-21",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "連刃",
      "description": "コンボスコア倍率が0.04上昇する。",
      "value": 0.04
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "windScroll",
        "sandals",
        "scarf"
      ],
      "effect": "mist",
      "skinSeed": 21
    }
  },
  {
    "id": "shinobi-ext-022",
    "name": "緋鳥",
    "description": "緋鳥——森の守り人の装い。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-22",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "時の余白",
      "description": "制限時間が3秒延長される。",
      "value": 3
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "headband",
        "woodenShuriken",
        "sandals"
      ],
      "effect": "wind",
      "skinSeed": 22
    }
  },
  {
    "id": "shinobi-ext-023",
    "name": "翠嵐",
    "description": "翠嵐——雨に濡れた蓑姿。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-23",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "完璧の型",
      "description": "ノーミス成功時に追加スコア+8を得る。",
      "value": 8
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "scroll",
        "coinBag",
        "crest"
      ],
      "effect": "fire",
      "skinSeed": 23
    }
  },
  {
    "id": "shinobi-ext-024",
    "name": "銀狐",
    "description": "銀狐——竹の里の修行着。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-24",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "whiteCloak",
        "mask",
        "armor"
      ],
      "effect": "fox",
      "skinSeed": 24
    }
  },
  {
    "id": "shinobi-ext-025",
    "name": "朱鷺",
    "description": "朱鷺——川辺で鍛えた身軽さ。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-25",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "moonCrest",
        "scarf",
        "scroll"
      ],
      "effect": "shadow",
      "skinSeed": 25
    }
  },
  {
    "id": "shinobi-ext-026",
    "name": "琥珀",
    "description": "琥珀——獣の気配を借りた装い。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-26",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "dawnSash",
        "dagger",
        "headband"
      ],
      "effect": "moon",
      "skinSeed": 26
    }
  },
  {
    "id": "shinobi-ext-027",
    "name": "瑠璃",
    "description": "瑠璃——古刹で授かった装束。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-27",
    "ability": {
      "type": "scoreMultiplier",
      "name": "鋭刃",
      "description": "獲得スコアが5%増加する。",
      "value": 1.05
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "shield",
        "armor",
        "mask"
      ],
      "effect": "lightning",
      "skinSeed": 27
    }
  },
  {
    "id": "shinobi-ext-028",
    "name": "真白",
    "description": "真白——雷を纏う特異な装備。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-28",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "連刃",
      "description": "コンボスコア倍率が0.04上昇する。",
      "value": 0.04
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "lightningMark",
        "armor",
        "dualBlades"
      ],
      "effect": "none",
      "skinSeed": 28
    }
  },
  {
    "id": "shinobi-ext-029",
    "name": "烏鴉",
    "description": "烏鴉——氷の気配を帯びた外套。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-29",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "時の余白",
      "description": "制限時間が3秒延長される。",
      "value": 3
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "foxTail",
        "mask",
        "scroll"
      ],
      "effect": "ember",
      "skinSeed": 29
    }
  },
  {
    "id": "shinobi-ext-030",
    "name": "白鷺",
    "description": "白鷺——天を仰ぐような威厳ある装い。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-30",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "完璧の型",
      "description": "ノーミス成功時に追加スコア+8を得る。",
      "value": 8
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "silverBlade",
        "shoulderPad",
        "headband"
      ],
      "effect": "water",
      "skinSeed": 30
    }
  },
  {
    "id": "shinobi-ext-031",
    "name": "鯉跳",
    "description": "鯉跳——里で鍛えた素朴な装い。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-31",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "scarf",
        "dagger",
        "headband"
      ],
      "effect": "gold",
      "skinSeed": 31
    }
  },
  {
    "id": "shinobi-ext-032",
    "name": "鷹爪",
    "description": "鷹爪——夜陰に溶ける装束。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-32",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "helmet",
        "shoulderPad",
        "scroll"
      ],
      "effect": "mist",
      "skinSeed": 32
    }
  },
  {
    "id": "shinobi-ext-033",
    "name": "猿飛",
    "description": "猿飛——砂煙を纏う旅装。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-33",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "wind",
      "skinSeed": 33
    }
  },
  {
    "id": "shinobi-ext-034",
    "name": "犬走",
    "description": "犬走——霧に隠れた忍装束。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-34",
    "ability": {
      "type": "scoreMultiplier",
      "name": "鋭刃",
      "description": "獲得スコアが5%増加する。",
      "value": 1.05
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "leafMark",
        "headband",
        "sandals"
      ],
      "effect": "fire",
      "skinSeed": 34
    }
  },
  {
    "id": "shinobi-ext-035",
    "name": "鹿威",
    "description": "鹿威——岩窟で磨いた武具。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-35",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "連刃",
      "description": "コンボスコア倍率が0.04上昇する。",
      "value": 0.04
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "mask",
        "sandals",
        "shortSword"
      ],
      "effect": "fox",
      "skinSeed": 35
    }
  },
  {
    "id": "shinobi-ext-036",
    "name": "熊胆",
    "description": "熊胆——鳥の羽を模した軽装。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-36",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "時の余白",
      "description": "制限時間が3秒延長される。",
      "value": 3
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "dualBlades",
        "redEyes",
        "scarf"
      ],
      "effect": "shadow",
      "skinSeed": 36
    }
  },
  {
    "id": "shinobi-ext-037",
    "name": "鶴翼",
    "description": "鶴翼——伝承の巻物を携えた姿。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-37",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "完璧の型",
      "description": "ノーミス成功時に追加スコア+8を得る。",
      "value": 8
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "blackFlame",
        "dualBlades",
        "mask"
      ],
      "effect": "moon",
      "skinSeed": 37
    }
  },
  {
    "id": "shinobi-ext-038",
    "name": "猫柳",
    "description": "猫柳——戦場を駆けた痕跡のある鎧。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-38",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "windScroll",
        "sandals",
        "scarf"
      ],
      "effect": "lightning",
      "skinSeed": 38
    }
  },
  {
    "id": "shinobi-ext-039",
    "name": "鰹刃",
    "description": "鰹刃——炎の紋章を背負う姿。",
    "rarity": "R",
    "skinClass": "ninja-skin-gen-39",
    "ability": {
      "type": "scoreMultiplier",
      "name": "迅影",
      "description": "獲得スコアが6%増加する。",
      "value": 1.06
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "headband",
        "woodenShuriken",
        "sandals"
      ],
      "effect": "none",
      "skinSeed": 39
    }
  },
  {
    "id": "shinobi-ext-040",
    "name": "赤星",
    "description": "赤星——天を仰ぐような威厳ある装い。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-40",
    "ability": {
      "type": "scoreMultiplier",
      "name": "烈撃",
      "description": "獲得スコアが9%増加する。",
      "value": 1.09
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "mask",
        "sandals",
        "shortSword"
      ],
      "effect": "fire",
      "skinSeed": 40
    }
  },
  {
    "id": "shinobi-ext-041",
    "name": "青嵐",
    "description": "青嵐——里で鍛えた素朴な装い。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-41",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "連鎖",
      "description": "コンボスコア倍率が0.07上昇する。",
      "value": 0.07
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "dualBlades",
        "redEyes",
        "scarf"
      ],
      "effect": "fox",
      "skinSeed": 41
    }
  },
  {
    "id": "shinobi-ext-042",
    "name": "黄龍",
    "description": "黄龍——夜陰に溶ける装束。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-42",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "延刻",
      "description": "制限時間が4秒延長される。",
      "value": 4
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "blackFlame",
        "dualBlades",
        "mask"
      ],
      "effect": "shadow",
      "skinSeed": 42
    }
  },
  {
    "id": "shinobi-ext-043",
    "name": "紫霞",
    "description": "紫霞——砂煙を纏う旅装。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-43",
    "ability": {
      "type": "streakRewardMultiplier",
      "name": "連続の恵み",
      "description": "連続成功報酬のコインが10%増加する。",
      "value": 1.1
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "windScroll",
        "sandals",
        "scarf"
      ],
      "effect": "moon",
      "skinSeed": 43
    }
  },
  {
    "id": "shinobi-ext-044",
    "name": "玄霧",
    "description": "玄霧——霧に隠れた忍装束。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-44",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "無欠の一撃",
      "description": "ノーミス成功時に追加スコア+15を得る。",
      "value": 15
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "headband",
        "woodenShuriken",
        "sandals"
      ],
      "effect": "lightning",
      "skinSeed": 44
    }
  },
  {
    "id": "shinobi-ext-045",
    "name": "朱雀",
    "description": "朱雀——岩窟で磨いた武具。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-45",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "戦利の目",
      "description": "撃破ボーナスで獲得するコインが12%増加する。",
      "value": 1.12
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "scroll",
        "coinBag",
        "crest"
      ],
      "effect": "none",
      "skinSeed": 45
    }
  },
  {
    "id": "shinobi-ext-046",
    "name": "白虎",
    "description": "白虎——鳥の羽を模した軽装。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-46",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "戦利の目",
      "description": "撃破ボーナスで獲得するコインが12%増加する。",
      "value": 1.12
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "whiteCloak",
        "mask",
        "armor"
      ],
      "effect": "ember",
      "skinSeed": 46
    }
  },
  {
    "id": "shinobi-ext-047",
    "name": "青龍",
    "description": "青龍——伝承の巻物を携えた姿。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-47",
    "ability": {
      "type": "scoreMultiplier",
      "name": "烈撃",
      "description": "獲得スコアが9%増加する。",
      "value": 1.09
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "moonCrest",
        "scarf",
        "scroll"
      ],
      "effect": "water",
      "skinSeed": 47
    }
  },
  {
    "id": "shinobi-ext-048",
    "name": "玄武",
    "description": "玄武——戦場を駆けた痕跡のある鎧。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-48",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "連鎖",
      "description": "コンボスコア倍率が0.07上昇する。",
      "value": 0.07
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "dawnSash",
        "dagger",
        "headband"
      ],
      "effect": "gold",
      "skinSeed": 48
    }
  },
  {
    "id": "shinobi-ext-049",
    "name": "麒麟",
    "description": "麒麟——炎の紋章を背負う姿。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-49",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "延刻",
      "description": "制限時間が4秒延長される。",
      "value": 4
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "shield",
        "armor",
        "mask"
      ],
      "effect": "mist",
      "skinSeed": 49
    }
  },
  {
    "id": "shinobi-ext-050",
    "name": "修羅",
    "description": "修羅——黄金の装飾が施された鎧。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-50",
    "ability": {
      "type": "streakRewardMultiplier",
      "name": "連続の恵み",
      "description": "連続成功報酬のコインが10%増加する。",
      "value": 1.1
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "lightningMark",
        "armor",
        "dualBlades"
      ],
      "effect": "wind",
      "skinSeed": 50
    }
  },
  {
    "id": "shinobi-ext-051",
    "name": "天誅",
    "description": "天誅——神域に触れたと言われる装束。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-51",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "無欠の一撃",
      "description": "ノーミス成功時に追加スコア+15を得る。",
      "value": 15
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "foxTail",
        "mask",
        "scroll"
      ],
      "effect": "fire",
      "skinSeed": 51
    }
  },
  {
    "id": "shinobi-ext-052",
    "name": "無月",
    "description": "無月——野山を駆ける軽装。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-52",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "戦利の目",
      "description": "撃破ボーナスで獲得するコインが12%増加する。",
      "value": 1.12
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "silverBlade",
        "shoulderPad",
        "headband"
      ],
      "effect": "fox",
      "skinSeed": 52
    }
  },
  {
    "id": "shinobi-ext-053",
    "name": "千鳥",
    "description": "千鳥——森の守り人の装い。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-53",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "戦利の目",
      "description": "撃破ボーナスで獲得するコインが12%増加する。",
      "value": 1.12
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "scarf",
        "dagger",
        "headband"
      ],
      "effect": "shadow",
      "skinSeed": 53
    }
  },
  {
    "id": "shinobi-ext-054",
    "name": "百鬼",
    "description": "百鬼——雨に濡れた蓑姿。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-54",
    "ability": {
      "type": "scoreMultiplier",
      "name": "烈撃",
      "description": "獲得スコアが9%増加する。",
      "value": 1.09
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "helmet",
        "shoulderPad",
        "scroll"
      ],
      "effect": "moon",
      "skinSeed": 54
    }
  },
  {
    "id": "shinobi-ext-055",
    "name": "六道",
    "description": "六道——竹の里の修行着。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-55",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "連鎖",
      "description": "コンボスコア倍率が0.07上昇する。",
      "value": 0.07
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "lightning",
      "skinSeed": 55
    }
  },
  {
    "id": "shinobi-ext-056",
    "name": "疾風丸",
    "description": "疾風丸——川辺で鍛えた身軽さ。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-56",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "延刻",
      "description": "制限時間が4秒延長される。",
      "value": 4
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "leafMark",
        "headband",
        "sandals"
      ],
      "effect": "none",
      "skinSeed": 56
    }
  },
  {
    "id": "shinobi-ext-057",
    "name": "火車",
    "description": "火車——獣の気配を借りた装い。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-57",
    "ability": {
      "type": "streakRewardMultiplier",
      "name": "連続の恵み",
      "description": "連続成功報酬のコインが10%増加する。",
      "value": 1.1
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "mask",
        "sandals",
        "shortSword"
      ],
      "effect": "ember",
      "skinSeed": 57
    }
  },
  {
    "id": "shinobi-ext-058",
    "name": "天斬",
    "description": "天斬——古刹で授かった装束。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-58",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "無欠の一撃",
      "description": "ノーミス成功時に追加スコア+15を得る。",
      "value": 15
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "dualBlades",
        "redEyes",
        "scarf"
      ],
      "effect": "water",
      "skinSeed": 58
    }
  },
  {
    "id": "shinobi-ext-059",
    "name": "地裂",
    "description": "地裂——雷を纏う特異な装備。",
    "rarity": "SR",
    "skinClass": "ninja-skin-gen-59",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "戦利の目",
      "description": "撃破ボーナスで獲得するコインが12%増加する。",
      "value": 1.12
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "blackFlame",
        "dualBlades",
        "mask"
      ],
      "effect": "gold",
      "skinSeed": 59
    }
  },
  {
    "id": "shinobi-ext-060",
    "name": "黒天",
    "description": "黒天——黄金の装飾が施された鎧。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-60",
    "ability": {
      "type": "scoreMultiplier",
      "name": "覇撃",
      "description": "獲得スコアが14%増加する。",
      "value": 1.14
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "moon",
      "skinSeed": 60
    }
  },
  {
    "id": "shinobi-ext-061",
    "name": "白煌",
    "description": "白煌——神域に触れたと言われる装束。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-61",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "富の巡り",
      "description": "撃破ボーナスで獲得するコインが22%増加する。",
      "value": 1.22
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "leafMark",
        "headband",
        "sandals"
      ],
      "effect": "lightning",
      "skinSeed": 61
    }
  },
  {
    "id": "shinobi-ext-062",
    "name": "紅蓮王",
    "description": "紅蓮王——野山を駆ける軽装。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-62",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "天衣無縫",
      "description": "コンボスコア倍率が0.10上昇する。",
      "value": 0.1
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "mask",
        "sandals",
        "shortSword"
      ],
      "effect": "none",
      "skinSeed": 62
    }
  },
  {
    "id": "shinobi-ext-063",
    "name": "蒼帝",
    "description": "蒼帝——森の守り人の装い。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-63",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "永刻",
      "description": "制限時間が6秒延長される。",
      "value": 6
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "dualBlades",
        "redEyes",
        "scarf"
      ],
      "effect": "ember",
      "skinSeed": 63
    }
  },
  {
    "id": "shinobi-ext-064",
    "name": "翠玉",
    "description": "翠玉——雨に濡れた蓑姿。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-64",
    "ability": {
      "type": "streakRewardMultiplier",
      "name": "連峰の報酬",
      "description": "連続成功報酬のコインが18%増加する。",
      "value": 1.18
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "blackFlame",
        "dualBlades",
        "mask"
      ],
      "effect": "water",
      "skinSeed": 64
    }
  },
  {
    "id": "shinobi-ext-065",
    "name": "金剛",
    "description": "金剛——竹の里の修行着。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-65",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "極意の一閃",
      "description": "ノーミス成功時に追加スコア+25を得る。",
      "value": 25
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "windScroll",
        "sandals",
        "scarf"
      ],
      "effect": "gold",
      "skinSeed": 65
    }
  },
  {
    "id": "shinobi-ext-066",
    "name": "銀翼",
    "description": "銀翼——川辺で鍛えた身軽さ。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-66",
    "ability": {
      "type": "timeRewardDoubleChance",
      "name": "時の幸運",
      "description": "連続成功の時間報酬が20%の確率で2倍になる。",
      "value": 0.2
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "headband",
        "woodenShuriken",
        "sandals"
      ],
      "effect": "mist",
      "skinSeed": 66
    }
  },
  {
    "id": "shinobi-ext-067",
    "name": "紫苑",
    "description": "紫苑——獣の気配を借りた装い。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-67",
    "ability": {
      "type": "scoreMultiplier",
      "name": "覇撃",
      "description": "獲得スコアが14%増加する。",
      "value": 1.14
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "scroll",
        "coinBag",
        "crest"
      ],
      "effect": "wind",
      "skinSeed": 67
    }
  },
  {
    "id": "shinobi-ext-068",
    "name": "深紅",
    "description": "深紅——古刹で授かった装束。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-68",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "富の巡り",
      "description": "撃破ボーナスで獲得するコインが22%増加する。",
      "value": 1.22
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "whiteCloak",
        "mask",
        "armor"
      ],
      "effect": "fire",
      "skinSeed": 68
    }
  },
  {
    "id": "shinobi-ext-069",
    "name": "氷華",
    "description": "氷華——雷を纏う特異な装備。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-69",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "天衣無縫",
      "description": "コンボスコア倍率が0.10上昇する。",
      "value": 0.1
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "moonCrest",
        "scarf",
        "scroll"
      ],
      "effect": "fox",
      "skinSeed": 69
    }
  },
  {
    "id": "shinobi-ext-070",
    "name": "炎獄",
    "description": "炎獄——氷の気配を帯びた外套。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-70",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "永刻",
      "description": "制限時間が6秒延長される。",
      "value": 6
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "dawnSash",
        "dagger",
        "headband"
      ],
      "effect": "shadow",
      "skinSeed": 70
    }
  },
  {
    "id": "shinobi-ext-071",
    "name": "雷帝",
    "description": "雷帝——天を仰ぐような威厳ある装い。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-71",
    "ability": {
      "type": "streakRewardMultiplier",
      "name": "連峰の報酬",
      "description": "連続成功報酬のコインが18%増加する。",
      "value": 1.18
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "shield",
        "armor",
        "mask"
      ],
      "effect": "moon",
      "skinSeed": 71
    }
  },
  {
    "id": "shinobi-ext-072",
    "name": "嵐神",
    "description": "嵐神——里で鍛えた素朴な装い。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-72",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "極意の一閃",
      "description": "ノーミス成功時に追加スコア+25を得る。",
      "value": 25
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "lightningMark",
        "armor",
        "dualBlades"
      ],
      "effect": "lightning",
      "skinSeed": 72
    }
  },
  {
    "id": "shinobi-ext-073",
    "name": "月光斬",
    "description": "月光斬——夜陰に溶ける装束。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-73",
    "ability": {
      "type": "timeRewardDoubleChance",
      "name": "時の幸運",
      "description": "連続成功の時間報酬が20%の確率で2倍になる。",
      "value": 0.2
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "foxTail",
        "mask",
        "scroll"
      ],
      "effect": "none",
      "skinSeed": 73
    }
  },
  {
    "id": "shinobi-ext-074",
    "name": "暁天",
    "description": "暁天——砂煙を纏う旅装。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-74",
    "ability": {
      "type": "scoreMultiplier",
      "name": "覇撃",
      "description": "獲得スコアが14%増加する。",
      "value": 1.14
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "silverBlade",
        "shoulderPad",
        "headband"
      ],
      "effect": "ember",
      "skinSeed": 74
    }
  },
  {
    "id": "shinobi-ext-075",
    "name": "宵闇",
    "description": "宵闇——霧に隠れた忍装束。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-75",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "富の巡り",
      "description": "撃破ボーナスで獲得するコインが22%増加する。",
      "value": 1.22
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "scarf",
        "dagger",
        "headband"
      ],
      "effect": "water",
      "skinSeed": 75
    }
  },
  {
    "id": "shinobi-ext-076",
    "name": "無双刃",
    "description": "無双刃——岩窟で磨いた武具。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-76",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "天衣無縫",
      "description": "コンボスコア倍率が0.10上昇する。",
      "value": 0.1
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "helmet",
        "shoulderPad",
        "scroll"
      ],
      "effect": "gold",
      "skinSeed": 76
    }
  },
  {
    "id": "shinobi-ext-077",
    "name": "虹色",
    "description": "虹色——鳥の羽を模した軽装。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-77",
    "ability": {
      "type": "timeBonusSeconds",
      "name": "永刻",
      "description": "制限時間が6秒延長される。",
      "value": 6
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "mist",
      "skinSeed": 77
    }
  },
  {
    "id": "shinobi-ext-078",
    "name": "龍炎",
    "description": "龍炎——伝承の巻物を携えた姿。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-78",
    "ability": {
      "type": "streakRewardMultiplier",
      "name": "連峰の報酬",
      "description": "連続成功報酬のコインが18%増加する。",
      "value": 1.18
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "leafMark",
        "headband",
        "sandals"
      ],
      "effect": "wind",
      "skinSeed": 78
    }
  },
  {
    "id": "shinobi-ext-079",
    "name": "鳳凰",
    "description": "鳳凰——戦場を駆けた痕跡のある鎧。",
    "rarity": "SSR",
    "skinClass": "ninja-skin-gen-79",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "極意の一閃",
      "description": "ノーミス成功時に追加スコア+25を得る。",
      "value": 25
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "mask",
        "sandals",
        "shortSword"
      ],
      "effect": "fire",
      "skinSeed": 79
    }
  },
  {
    "id": "shinobi-ext-080",
    "name": "終焉",
    "description": "終焉——氷の気配を帯びた外套。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-80",
    "ability": {
      "type": "scoreMultiplier",
      "name": "覇道の刃",
      "description": "獲得スコアが18%増加する。",
      "value": 1.18
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "scarf",
        "dagger",
        "headband"
      ],
      "effect": "ember",
      "skinSeed": 80
    }
  },
  {
    "id": "shinobi-ext-081",
    "name": "創世",
    "description": "創世——天を仰ぐような威厳ある装い。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-81",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "財宝招来",
      "description": "撃破ボーナスで獲得するコインが35%増加する。",
      "value": 1.35
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "helmet",
        "shoulderPad",
        "scroll"
      ],
      "effect": "water",
      "skinSeed": 81
    }
  },
  {
    "id": "shinobi-ext-082",
    "name": "万象",
    "description": "万象——里で鍛えた素朴な装い。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-82",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "無限連鎖",
      "description": "コンボスコア倍率が0.12上昇する。",
      "value": 0.12
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "gold",
      "skinSeed": 82
    }
  },
  {
    "id": "shinobi-ext-083",
    "name": "不動",
    "description": "不動——夜陰に溶ける装束。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-83",
    "ability": {
      "type": "streakMilestoneReduction",
      "name": "早天の報い",
      "description": "最初の連続成功報酬が3問で発動する。",
      "value": 1
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "leafMark",
        "headband",
        "sandals"
      ],
      "effect": "mist",
      "skinSeed": 83
    }
  },
  {
    "id": "shinobi-ext-084",
    "name": "刹那",
    "description": "刹那——砂煙を纏う旅装。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-84",
    "ability": {
      "type": "streakShield",
      "name": "不動の心",
      "description": "1回だけミスしても連続成功ゲージがリセットされない。",
      "value": 1
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "mask",
        "sandals",
        "shortSword"
      ],
      "effect": "wind",
      "skinSeed": 84
    }
  },
  {
    "id": "shinobi-ext-085",
    "name": "永劫",
    "description": "永劫——霧に隠れた忍装束。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-85",
    "ability": {
      "type": "timeRewardDoubleChance",
      "name": "時の覇者",
      "description": "連続成功の時間報酬が30%の確率で2倍になる。",
      "value": 0.3
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "dualBlades",
        "redEyes",
        "scarf"
      ],
      "effect": "fire",
      "skinSeed": 85
    }
  },
  {
    "id": "shinobi-ext-086",
    "name": "無限",
    "description": "無限——岩窟で磨いた武具。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-86",
    "ability": {
      "type": "gachaDuplicateCoinMultiplier",
      "name": "重宝の目利き",
      "description": "ガチャ被り時の獲得コインが15%増加する。",
      "value": 1.15
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "blackFlame",
        "dualBlades",
        "mask"
      ],
      "effect": "fox",
      "skinSeed": 86
    }
  },
  {
    "id": "shinobi-ext-087",
    "name": "覇道",
    "description": "覇道——鳥の羽を模した軽装。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-87",
    "ability": {
      "type": "scoreMultiplier",
      "name": "覇道の刃",
      "description": "獲得スコアが18%増加する。",
      "value": 1.18
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "windScroll",
        "sandals",
        "scarf"
      ],
      "effect": "shadow",
      "skinSeed": 87
    }
  },
  {
    "id": "shinobi-ext-088",
    "name": "天変",
    "description": "天変——伝承の巻物を携えた姿。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-88",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "財宝招来",
      "description": "撃破ボーナスで獲得するコインが35%増加する。",
      "value": 1.35
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "headband",
        "woodenShuriken",
        "sandals"
      ],
      "effect": "moon",
      "skinSeed": 88
    }
  },
  {
    "id": "shinobi-ext-089",
    "name": "地異",
    "description": "地異——戦場を駆けた痕跡のある鎧。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-89",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "無限連鎖",
      "description": "コンボスコア倍率が0.12上昇する。",
      "value": 0.12
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "scroll",
        "coinBag",
        "crest"
      ],
      "effect": "lightning",
      "skinSeed": 89
    }
  },
  {
    "id": "shinobi-ext-090",
    "name": "隠密",
    "description": "隠密——炎の紋章を背負う姿。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-90",
    "ability": {
      "type": "streakMilestoneReduction",
      "name": "早天の報い",
      "description": "最初の連続成功報酬が3問で発動する。",
      "value": 1
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "whiteCloak",
        "mask",
        "armor"
      ],
      "effect": "none",
      "skinSeed": 90
    }
  },
  {
    "id": "shinobi-ext-091",
    "name": "無形",
    "description": "無形——黄金の装飾が施された鎧。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-91",
    "ability": {
      "type": "streakShield",
      "name": "不動の心",
      "description": "1回だけミスしても連続成功ゲージがリセットされない。",
      "value": 1
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "moonCrest",
        "scarf",
        "scroll"
      ],
      "effect": "ember",
      "skinSeed": 91
    }
  },
  {
    "id": "shinobi-ext-092",
    "name": "幻影",
    "description": "幻影——神域に触れたと言われる装束。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-92",
    "ability": {
      "type": "timeRewardDoubleChance",
      "name": "時の覇者",
      "description": "連続成功の時間報酬が30%の確率で2倍になる。",
      "value": 0.3
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "dawnSash",
        "dagger",
        "headband"
      ],
      "effect": "water",
      "skinSeed": 92
    }
  },
  {
    "id": "shinobi-ext-093",
    "name": "虚空",
    "description": "虚空——野山を駆ける軽装。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-93",
    "ability": {
      "type": "gachaDuplicateCoinMultiplier",
      "name": "重宝の目利き",
      "description": "ガチャ被り時の獲得コインが15%増加する。",
      "value": 1.15
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "shield",
        "armor",
        "mask"
      ],
      "effect": "gold",
      "skinSeed": 93
    }
  },
  {
    "id": "shinobi-ext-094",
    "name": "神威",
    "description": "神威——森の守り人の装い。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-94",
    "ability": {
      "type": "scoreMultiplier",
      "name": "覇道の刃",
      "description": "獲得スコアが18%増加する。",
      "value": 1.18
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "lightningMark",
        "armor",
        "dualBlades"
      ],
      "effect": "mist",
      "skinSeed": 94
    }
  },
  {
    "id": "shinobi-ext-095",
    "name": "烈風",
    "description": "烈風——雨に濡れた蓑姿。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-95",
    "ability": {
      "type": "stageCoinMultiplier",
      "name": "財宝招来",
      "description": "撃破ボーナスで獲得するコインが35%増加する。",
      "value": 1.35
    },
    "visual": {
      "pose": "oni",
      "accessories": [
        "foxTail",
        "mask",
        "scroll"
      ],
      "effect": "wind",
      "skinSeed": 95
    }
  },
  {
    "id": "shinobi-ext-096",
    "name": "極意",
    "description": "極意——竹の里の修行着。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-96",
    "ability": {
      "type": "comboMultiplierBonus",
      "name": "無限連鎖",
      "description": "コンボスコア倍率が0.12上昇する。",
      "value": 0.12
    },
    "visual": {
      "pose": "basic",
      "accessories": [
        "silverBlade",
        "shoulderPad",
        "headband"
      ],
      "effect": "fire",
      "skinSeed": 96
    }
  },
  {
    "id": "shinobi-ext-097",
    "name": "超越",
    "description": "超越——川辺で鍛えた身軽さ。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-97",
    "ability": {
      "type": "streakMilestoneReduction",
      "name": "早天の報い",
      "description": "最初の連続成功報酬が3問で発動する。",
      "value": 1
    },
    "visual": {
      "pose": "shadow",
      "accessories": [
        "scarf",
        "dagger",
        "headband"
      ],
      "effect": "fox",
      "skinSeed": 97
    }
  },
  {
    "id": "shinobi-ext-098",
    "name": "絶対",
    "description": "絶対——獣の気配を借りた装い。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-98",
    "ability": {
      "type": "streakShield",
      "name": "不動の心",
      "description": "1回だけミスしても連続成功ゲージがリセットされない。",
      "value": 1
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "helmet",
        "shoulderPad",
        "scroll"
      ],
      "effect": "shadow",
      "skinSeed": 98
    }
  },
  {
    "id": "shinobi-ext-099",
    "name": "天下",
    "description": "天下——古刹で授かった装束。",
    "rarity": "UR",
    "skinClass": "ninja-skin-gen-99",
    "ability": {
      "type": "timeRewardDoubleChance",
      "name": "時の覇者",
      "description": "連続成功の時間報酬が30%の確率で2倍になる。",
      "value": 0.3
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "moon",
      "skinSeed": 99
    }
  },
  {
    "id": "shinobi-ext-100",
    "name": "天津甦",
    "description": "天津甦——炎の紋章を背負う姿。",
    "rarity": "SHINNIN",
    "skinClass": "ninja-skin-gen-100",
    "ability": {
      "type": "streakMilestoneReduction",
      "name": "神域の刻",
      "description": "最初の連続成功報酬が3問で発動する。",
      "value": 1
    },
    "visual": {
      "pose": "silver",
      "accessories": [
        "foxTail",
        "mask",
        "scroll"
      ],
      "effect": "mist",
      "skinSeed": 100
    }
  },
  {
    "id": "shinobi-ext-101",
    "name": "黄泉返",
    "description": "黄泉返——黄金の装飾が施された鎧。",
    "rarity": "SHINNIN",
    "skinClass": "ninja-skin-gen-101",
    "ability": {
      "type": "streakShield",
      "name": "不壊の意志",
      "description": "2回までミスしても連続成功ゲージがリセットされない。",
      "value": 2
    },
    "visual": {
      "pose": "wind",
      "accessories": [
        "silverBlade",
        "shoulderPad",
        "headband"
      ],
      "effect": "wind",
      "skinSeed": 101
    }
  },
  {
    "id": "shinobi-ext-102",
    "name": "八百万",
    "description": "八百万——神域に触れたと言われる装束。",
    "rarity": "SHINNIN",
    "skinClass": "ninja-skin-gen-102",
    "ability": {
      "type": "timeRewardDoubleChance",
      "name": "永劫の時",
      "description": "連続成功の時間報酬が40%の確率で2倍になる。",
      "value": 0.4
    },
    "visual": {
      "pose": "aggressive",
      "accessories": [
        "scarf",
        "dagger",
        "headband"
      ],
      "effect": "fire",
      "skinSeed": 102
    }
  },
  {
    "id": "shinobi-ext-103",
    "name": "御柱茜",
    "description": "御柱茜——野山を駆ける軽装。",
    "rarity": "SHINNIN",
    "skinClass": "ninja-skin-gen-103",
    "ability": {
      "type": "scoreMultiplier",
      "name": "神威の一撃",
      "description": "獲得スコアが25%増加する。",
      "value": 1.25
    },
    "visual": {
      "pose": "twin",
      "accessories": [
        "helmet",
        "shoulderPad",
        "scroll"
      ],
      "effect": "fox",
      "skinSeed": 103
    }
  },
  {
    "id": "shinobi-ext-104",
    "name": "界裂",
    "description": "界裂——森の守り人の装い。",
    "rarity": "SHINNIN",
    "skinClass": "ninja-skin-gen-104",
    "ability": {
      "type": "perfectScoreBonus",
      "name": "無漏の極意",
      "description": "ノーミス成功時に追加スコア+40を得る。",
      "value": 40
    },
    "visual": {
      "pose": "storm",
      "accessories": [
        "oniMask",
        "shoulderPad",
        "crest"
      ],
      "effect": "shadow",
      "skinSeed": 104
    }
  }
] as const
